### ISSUE TITLE
Launch can't be closed when the client is created using a already obtained uuid

### ISSUE THREAD

**Issue by Kimovac** [reportportal/client-Python#242] opened 2024-10-23 22:40 UTC
https://github.com/reportportal/client-Python/blob/f9b77b8c0c923bdc1c0ff3b4e931801e85c3c865/reportportal_client/client.py#L706

Description:
I found that when I try to finish a launch when the client is created with a provided launch_uuid. The launch is unable to close. The provided line is the issue. When I set it to True, it works as it should be. I'm not 100% sure I'm using the API correctly, But this seems like a bug to me.

Steps to Reproduce

1. Create a launch in one program and retrieve the uuid. And close the said program
2. Try to close a launch in a another program using the uuid from the frist program

Actual behavior:
The launch isn't closed

Expected:
The launch is closed

Package versions
report-client version is 5.5.9

**Comment by HardNorth** [comment] 2024-10-24 05:19
@Kimovac, No, it's by design. If you pass Launch UUID, then you are responsible for Launch closing. This is done to not close Launches many times during the run.

**Closed by HardNorth** 2024-10-24 05:19 UTC

**Comment by HardNorth** [comment] 2024-10-24 09:21
@HardNorth Either by the same client you created the Launch, either by http request as, for example, here: https://github.com/reportportal/examples-python/blob/master/robotframework/run-pabot.sh
